name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
        API_URL: https://imdb-internet-movie-database-unofficial.p.rapidapi.com
        Key: cf1f9e357bmshb1965fc9f8cec9ap1a3aebjsn067152a7b766
        Host: imdb-internet-movie-database-unofficial.p.rapidapi.com